# Generated by Django 5.0.2 on 2024-02-26 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("tags", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("video_file", models.FileField(upload_to="Emotisement/%y")),
            ],
        ),
        migrations.CreateModel(
            name="VideoEmotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotions_and_timestamp", models.JSONField(null=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emo.video"
                    ),
                ),
            ],
        ),
    ]
