# Generated by Django 5.0.6 on 2024-05-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo.video')),
            ],
        ),
    ]
